name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Packages
        uses: docker/login-action@v1 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKENN }}
          registry: docker.pkg.github.com
          
      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: Elhemist/product-delivery:latest
